=== ijimae118/Lybrary/hk2/MSJ_BT_lop_XML/XML/src/d02_Book.xsd
<?xml version="1.0"?>
<!--
Mo ta cau truc 1 quyen sach.
1 quyen sach bao gom :ma so, tua ,tac gia,don gia,ngay xb,ton kho
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
   
    <xs:element name="Book" >
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded"><!--thi them vao day no chi lam tang so phan tu ben duoi vo han,ko tu lam tang book ,phai tu bam phan tu book -->
                <xs:element name="ID" type="xs:string" />
                <xs:element name="title" type="xs:string" />
                <xs:element name="author" type="xs:string" minOccurs="1" maxOccurs="3" />
                <xs:element name="price" type="xs:positiveInteger" /><!--nhi phan :Binary,so thi :numeric-->
                <xs:element name="date" type="xs:date" />
                <xs:element name="active" type="xs:boolean" /><!-- boolean chi dc nhap true or false-->
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ijimae118/Lybrary/hk2/MSJ_BT_lop_XML/XML/src/d02_Book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<Book
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='d02_Book.xsd'><!--sữa thành d02_Book.xsd thi ko đc vì cấu truc ko giong nen validate ko dc-->
    <ID>B01</ID>
    <title>Lap Trinh Web Co Ban</title>
    <author>Aptech</author>
    <author>Microsoft</author>
    <author>FPT Aptech</author>
    <price>12000</price>
    <date>2018-10-24</date>
    <active>true</active>
</Book>
