=== ijimae118/Lybrary/hk2/MSJ_BT_lop_XML/XML/src/d02_Book2.xsd
<?xml version="1.0"?>
<!--
Mo ta cau truc thu quyen sach.
1 quyen sach bao gom :ma so, tua ,tac gia,don gia,ngay xb,ton kho
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="Libary">
        <xs:complexType>
            <xs:sequence>
                 <xs:element name="Book" type="BookType"
                             maxOccurs="unbounded" /><!--la ko gioi han-->
            </xs:sequence>
        </xs:complexType>
    </xs:element>   
   



        <xs:complexType name="BookType">
            <xs:sequence>
                <xs:element name="ID" type="xs:string" />
                <xs:element name="title" type="xs:string" />
                <xs:element name="author" type="xs:string" minOccurs='1' maxOccurs='3' />
                <xs:element name="price" type="xs:positiveInteger" /><!--nhi phan :Binary,so thi :numeric-->
                <xs:element name="date" type="xs:date" />
                <xs:element name="active" type="xs:boolean" /><!-- boolean chi dc nhap true or false-->
            </xs:sequence>
        </xs:complexType>
</xs:schema>

=== ijimae118/Lybrary/hk2/MSJ_BT_lop_XML/XML/src/d02_Book2.xml
<?xml version="1.0" encoding="UTF-8"?>


<Libary
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='d02_Book2.xsd'>
    <Book>
        <ID>B01</ID>
        <title>Lap trinh C</title>
        <author>Ms Team</author>
        <price>120</price>
        <date>2000-01-19</date>
        <active>true</active>
    </Book>
    <Book>
        <ID>B02</ID>
        <title>Thiet Ke Web</title>
        <author>Aptech</author>
        <price>200</price>
        <date>1990-09-06</date>
        <active>false</active>
    </Book>
    <Book>
        <ID>B03</ID>
        <title>Quan tri du an</title>
        <author>Ms Team</author>
        <price>300</price>
        <date>2019-03-31</date>
        <active>true</active>
    </Book>
</Libary>
