=== ijimae118/Lybrary/hk2/MSJ_BT_lop_XML/XML/src/d02_Nhanvien.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Mo ta cau truc ho so nhan vien,bao gom nhieu nhan vien.
Moi nhan vien, se co thuoc tinh [maso (duy nhat),gioi tinh(nam/nu)],
                     ho ten , chuc vu,luong,bo phan
-->


<!ELEMENT HoSoNhanVien (NhanVien+)>
<!ELEMENT NhanVien (Ten ,ChucVu,Luong,BoPhan)>
<!ELEMENT Ten (#PCDATA)>
<!ELEMENT ChucVu (#PCDATA)>
<!ELEMENT Luong (#PCDATA)>
<!ELEMENT BoPhan (#PCDATA)>

<!ATTLIST NhanVien MaSo ID #REQUIRED
         GioiTinh (Nam|Nu) #REQUIRED >

=== ijimae118/Lybrary/hk2/MSJ_BT_lop_XML/XML/src/d02_NhanVien.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To ho nhan vien,dua theo cau truc mo ta d02_nhanvien.dtd
Bo phan:Ke Toan ,Quan tri ,San Xuat ,Van phong
-->

<!DOCTYPE HoSoNhanVien SYSTEM 'd02_Nhanvien.dtd'[
    <!ENTITY KT "Ke Toan">
    <!ENTITY VP "Van Phong">
    <!ENTITY SX "San Xuat">
    <!ENTITY QT "Quan Tri - Nhan Su">
]>
<HoSoNhanVien>
    <NhanVien MaSo="NV1" GioiTinh="Nam">
        <Ten>Nguyen Ngoc Thach</Ten>
        <ChucVu>Giam Doc</ChucVu>
        <Luong>1</Luong>
        <BoPhan>&VP;</BoPhan>
    </NhanVien>
    <NhanVien MaSo="NV2" GioiTinh="Nu">
        <Ten>Dang Tieu Chi</Ten>
        <ChucVu>Nhan Vien</ChucVu>
        <Luong>100</Luong>
        <BoPhan>&QT;</BoPhan>
    </NhanVien>
    <NhanVien MaSo="" GioiTinh="">
        <Ten></Ten>
        <ChucVu></ChucVu>
        <Luong></Luong>
        <BoPhan></BoPhan>        
    </NhanVien>
</HoSoNhanVien>
